spring:
  h2:
    console:
      enabled: true  # ??? ??? ??? (? UI)
      path: /h2-console # H2 ?? ???? ?? URL ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test # ???? ??
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update